#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "peertube-search-index"
name = "PeerTube search-index"
description.en = "Search engine for PeerTube videos and channels"
description.fr = "Moteur de recherche de vidéos et chaînes PeerTube"

version = "2025.10.28~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-only"
website = "https://search.joinpeertube.org/"
demo = "https://search.joinpeertube.org/"
code = "https://framagit.org/framasoft/peertube/search-index"

fund = "https://framasoft.org/fr/#support"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "2000M"
ram.build = "2000M"
ram.runtime = "2000M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://framagit.org/framasoft/peertube/search-index/-/archive/0f2da47313ebf83a9a86dcc20556beb0542b687c/search-index-0f2da47313ebf83a9a86dcc20556beb0542b687c.tar.bz2"
    sha256 = "a33ca31f86f4f0ca93c484d6d8f78dbc543455fe0150521fcdf40f4c0e5d1f85"
    # Unused because of submodules...
    prefetch = false
    autoupdate.strategy = "latest_gitlab_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095
    meilisearch.default = 17070

    [resources.apt]
    packages = "git"

    [resources.apt.extras.yarn]
    repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    packages = ["yarn"]

    [resources.nodejs]
    version = "18"
