#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "peertube-search-index"
name = "PeerTube search-index"
description.en = "Search engine for PeerTube videos and channels"
description.fr = "Moteur de recherche de vidéos et chaînes PeerTube"

version = "2025.03.31~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-only"
website = "https://search.joinpeertube.org/"
demo = "https://search.joinpeertube.org/"
code = "https://framagit.org/framasoft/peertube/search-index"

fund = "https://framasoft.org/fr/#support"

[integration]
yunohost = ">= 11.2"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"

sso = "not_relevant"

disk = "2000M"
ram.build = "2000M"
ram.runtime = "2000M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://framagit.org/framasoft/peertube/search-index/-/archive/3d23a3ecc7e324dd070f023936b3c6d61b101e12/search-index-3d23a3ecc7e324dd070f023936b3c6d61b101e12.tar.bz2"
    sha256 = "4f4da065ae9b5952818c8d9e48198a2e8a09718fd1d3b3f4c245e09f2d6a35f4"
    # Unused because of submodules...
    prefetch = false
    autoupdate.strategy = "latest_gitlab_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095
    meilisearch.default = 17070

    [resources.apt]
    packages = "git"

    [resources.apt.extras.yarn]
    repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    packages = ["yarn"]
