#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "peertube-search-index"
name = "PeerTube search-index"
description.en = "Search engine for PeerTube videos and channels"
description.fr = "Moteur de recherche de vidéos et chaînes PeerTube"

version = "1.0.0~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-only"
website = "https://search.joinpeertube.org/"
demo = "https://search.joinpeertube.org/"
admindoc = "https://framagit.org/framasoft/peertube/search-index"
code = "https://framagit.org/framasoft/peertube/search-index"
fund = "https://framasoft.org/fr/#support"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "2000M"
ram.build = "2000M"
ram.runtime = "2000M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://framagit.org/framasoft/peertube/search-index/-/archive/v1.0.0/search-index-v1.0.0.tar.bz2"
    sha256 = "ac45e299480cd87e824fcf9fb5f48446985c58079e8c8d10d34f3cc3492b3267"
    # Unused because of submodules...
    prefetch = false
    autoupdate.strategy = "latest_gitlab_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = ["git", ]

    [resources.apt.extras.meilisearch]
    repo = "deb https://apt.fury.io/meilisearch/ /"
    # key = "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    packages = ["meilisearch"]

    [resources.apt.extras.yarn]
    repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    packages = ["yarn"]
