#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "peertube-search-index"
name = "PeerTube search-index"
description.en = "Search engine for PeerTube videos and channels"
description.fr = "Moteur de recherche de vidéos et chaînes PeerTube"

version = "2026.04.28~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-only"
website = "https://search.joinpeertube.org/"
demo = "https://search.joinpeertube.org/"
code = "https://framagit.org/framasoft/peertube/search-index"

fund = "https://framasoft.org/fr/#support"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "2000M"
ram.build = "2000M"
ram.runtime = "2000M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://framagit.org/framasoft/peertube/search-index/-/archive/fd34185e64b4901fe6dd212a7805239a7cc51700/search-index-fd34185e64b4901fe6dd212a7805239a7cc51700.tar.bz2"
    sha256 = "4de98f911a37f6b818834f125e89c13a2c4ea8b1b11bbe241d1789143b870caa"
    # Unused because of submodules...
    prefetch = false
    autoupdate.strategy = "latest_gitlab_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095
    meilisearch.default = 17070

    [resources.apt]
    packages = "git"

    [resources.nodejs]
    version = "20"
