#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.63fe9f9406b112c086b23f68aaaee3d3d990b862.name = "Last packaging v1 version"
