listen:
  hostname: 'localhost'
  port: __PORT__

webserver:
  https: false
  hostname: 'localhost'
  port: __PORT__

meilisearch:
  host: 'http://127.0.0.1:7700'

  api_key: null

  indexes:
    videos: 'peertube-index-videos'
    channels: 'peertube-index-channels'
    playlists: 'peertube-index-playlists'

log:
  level: 'debug' # debug/info/warning/error

search-instance:
  name: 'PeerTube Search Index'

  # Set an image instead of displaying your website title in text at the top of the search page
  # Must be a relative URL. For example if you use a theme: /theme/mytheme/img/title.svg
  name_image: ''

  # The image between the title and the search bar
  search_image: ''

  description: 'A search engine of PeerTube videos and channels, developed by Framasoft'
  legal_notices_url: ''
  theme: 'default'

instances-index:
  # Contains PeerTube instance hosts the indexer will index
  # Must answer the following format: https://framagit.org/framasoft/peertube/instances-peertube#peertube-auto-follow-global-search
  url: 'https://instances.joinpeertube.org/api/v1/instances/hosts'

  # A public URL that will be displayed in the search page
  # So your users can see what instances your search instance indexed
  public_url: 'https://instances.joinpeertube.org'

  # Useful to do tests
  whitelist:
    enabled: false
    hosts: null

videos-search:
  # Allow client to send browser language to boost results score that are in these languages
  boost-languages:
    enabled: true

  # Add ability to change videos search fields boost and match value
  # See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html for more information
  #
  # If boost == 0, the field will not be part of the search
  #
  # match_type could be 'default' or 'phrase'
  #  * default: use default Elastic Search match query, including fuzziness
  #  * phrase: use Elastic Search phrase match query
  search-fields:
    uuid:
      boost: 100
      match_type: 'default'
    short-uuid:
      boost: 100
      match_type: 'default'
    name:
      boost: 5
      match_type: 'default'
    description:
      boost: 1
      match_type: 'phrase'
    tags:
      boost: 2
      match_type: 'default'
    account-display-name:
      boost: 2
      match_type: 'default'
    channel-display-name:
      boost: 2
      match_type: 'default'

channels-search:
  # Add ability to change channels search fields boost and match value
  # See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html for more information
  #
  # If boost == 0, the field will not be part of the search
  #
  # match_type could be 'default' or 'phrase'
  #  * default: use default Elastic Search match query, including fuzziness
  #  * phrase: use Elastic Search phrase match query
  search-fields:
    name:
      boost: 5
      match_type: 'default'
    description:
      boost: 1
      match_type: 'phrase'
    display-name:
      boost: 3
      match_type: 'default'
    account-display-name:
      boost: 2
      match_type: 'default'

playlists-search:
  # Add ability to change playlists search fields boost and match value
  # See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html for more information
  #
  # If boost == 0, the field will not be part of the search
  #
  # match_type could be 'default' or 'phrase'
  #  * default: use default Elastic Search match query, including fuzziness
  #  * phrase: use Elastic Search phrase match query
  search-fields:
    uuid:
      boost: 100
      match_type: 'default'
    short-uuid:
      boost: 100
      match_type: 'default'
    display-name:
      boost: 5
      match_type: 'default'
    description:
      boost: 1
      match_type: 'phrase'

api:
  # Blacklist hosts that will not be returned by the search API
  blacklist:
    enabled: false
    # Array of hosts
    hosts: null
