#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  # Path to source
  alias __INSTALL_DIR__/sources/;

  proxy_pass http://localhost:__PORT__;

  include proxy_params_no_auth;
}
