listen:
  hostname: 'localhost'
  port: __PORT__

webserver:
  https: false
  hostname: 'localhost'
  port: __PORT__

elastic-search:
  hostname: 'localhost'
  port: __ES_PORT__
  indexes:
    videos: '__APP__-videos'
    channels: '__APP__-channels'
    playlists: '__APP__-playlists'
