#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers
source ynh_sources

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir/sources"

chown -R "$app:www-data" "$install_dir"

#=================================================
# INSTALL MEILISEARCH
#=================================================
ynh_script_progression "Installing Meilisearch..."

ynh_exec_as_app mkdir -p "$install_dir/meilisearch"
pushd "$install_dir/meilisearch"
    ynh_exec_as_app curl -L https://install.meilisearch.com | ynh_exec_as_app sh
popd

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="default.yaml" --destination="$install_dir/sources/config/production.yaml"
ynh_config_add --template="config.toml" --destination="$install_dir/meilisearch/config.toml"

#=================================================
# INSTALL NODEJS
#=================================================
ynh_script_progression "Installing NodeJS..."

ynh_nodejs_install

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="$app search index daemon"

ynh_config_add_systemd --service="$app-meilisearch" --template="meilisearch.service"
yunohost service add "$app-meilisearch" --description="$app Meilisearch daemon"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# BUILDING
#=================================================
ynh_script_progression "Building..."

pushd "$install_dir/sources"
    ynh_hide_warnings ynh_exec_as_app yarn install --pure-lockfile
    ynh_exec_as_app mkdir -p "dist"
    ynh_hide_warnings ynh_exec_as_app npm run build
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app-meilisearch" --action="start" --log_path="systemd"
ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Server listening on port"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
