#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers
source ../settings/scripts/ynh_0-utils
source ../settings/scripts/ynh_sources

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# INSTALL NODEJS
#=================================================
ynh_script_progression "Reinstalling NodeJS..."

ynh_nodejs_install

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="$app search index daemon"

ynh_restore "/etc/systemd/system/$app-meilisearch.service"
systemctl enable "$app-meilisearch.service" --quiet
yunohost service add "$app-meilisearch" --description="$app Meilisearch daemon"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app-meilisearch" --action="start" --log_path="systemd"
ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Server listening on port"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
