#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd" --wait_until="Stopped $app search index daemon"

#=================================================
# INSTALL NODEJS
#=================================================
ynh_script_progression "Updating NodeJS..."

ynh_nodejs_install

#=================================================
# START ELASTICSEARCH
#=================================================
ynh_script_progression "Starting elasticsearch..."

systemctl enable elasticsearch.service --quiet
systemctl start elasticsearch.service

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# Move git repository one step lower
if [ -d "$install_dir/.git" ]; then
    mkdir "${install_dir}__tmp__"
    mv "$install_dir" "${install_dir}__tmp__/sources"
    mv "${install_dir}__tmp__" "$install_dir"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

_git_clone_or_pull "$install_dir/sources"

#=================================================
# BUILDING
#=================================================
ynh_script_progression "Building..."

pushd "$install_dir/sources"
    ynh_hide_warnings ynh_exec_as_app yarn install --pure-lockfile
    ynh_exec_as_app mkdir -p "dist"
    ynh_hide_warnings ynh_exec_as_app npm run build
popd

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating a config file..."

ynh_config_add --template="default.yaml" --destination="$install_dir/sources/config/production.yaml"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="$app search index daemon"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --wait_until="Server listening on port"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
